org.gradle.jvmargs=-Xmx1G

# Mod Properties
mod_id=statisticsupdater
mod_name=Statistics Updater
mod_description=Extends the /scoreboard command to add functionality for updating scoreboards that use statistics criteria

version=0.2.0-26.2

# Publishing
maven_group=xyz.eclipseisoffline
archives_base_name=statisticsupdater

release_type=STABLE
modrinth_project_id=sw5IYd9j
github_repository=eclipseisoffline/statistics-updater
git_branch=main
